### ISSUE TITLE
Nim version check fails on 0.19.0

### ISSUE THREAD

**Issue by jorisbontje** [bluenote10/NimData#30]
The nim version check `when NimMinor >= 18 and NimPatch > 0`
 in https://github.com/bluenote10/NimData/blob/master/src/nimdata/schema_parser.nim#L176-L179
 doesn't work correctly on 0.19.0 (as `NimPatch` is `0` again) so it falls back on old `times` code which causes the compilation error:
```
../../../.nimble/pkgs/nimdata-0.1.0/nimdata/schema_parser.nim(179, 27)
Error: type mismatch: got <int literal(0)> but expected 'Time = object'
```
A better solution would be to use:
`when (NimMajor, NimMinor, NimPatch) > (0, 18, 0)`

Note that this same version check also happens on some other location throughout the codebase and would also cause compilation failures for different code paths.
